// <auto-generated />
using BrightPay.TakeHome.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrightPay.TakeHome.Web.Data.Migrations
{
    [DbContext(typeof(CheckoutDbContext))]
    [Migration("20260624010052_InitialCheckoutCatalog")]
    partial class InitialCheckoutCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BrightPay.TakeHome.Web.Data.CheckoutOfferEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<decimal>("FixedPriceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.HasIndex("Sku", "State");

                    b.ToTable("CheckoutOffers", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "A-3-FOR-130",
                            FixedPriceAmount = 130m,
                            Quantity = 3,
                            Sku = "A",
                            State = 1,
                            Type = 1
                        },
                        new
                        {
                            Code = "B-2-FOR-45",
                            FixedPriceAmount = 45m,
                            Quantity = 2,
                            Sku = "B",
                            State = 1,
                            Type = 1
                        });
                });

            modelBuilder.Entity("BrightPay.TakeHome.Web.Data.CheckoutProductEntity", b =>
                {
                    b.Property<string>("Sku")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("UnitPriceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Sku");

                    b.HasIndex("IsActive");

                    b.ToTable("CheckoutProducts", (string)null);

                    b.HasData(
                        new
                        {
                            Sku = "A",
                            IsActive = true,
                            UnitPriceAmount = 50m
                        },
                        new
                        {
                            Sku = "B",
                            IsActive = true,
                            UnitPriceAmount = 30m
                        },
                        new
                        {
                            Sku = "C",
                            IsActive = true,
                            UnitPriceAmount = 20m
                        },
                        new
                        {
                            Sku = "D",
                            IsActive = true,
                            UnitPriceAmount = 15m
                        });
                });

            modelBuilder.Entity("BrightPay.TakeHome.Web.Data.CheckoutOfferEntity", b =>
                {
                    b.HasOne("BrightPay.TakeHome.Web.Data.CheckoutProductEntity", "Product")
                        .WithMany("Offers")
                        .HasForeignKey("Sku")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BrightPay.TakeHome.Web.Data.CheckoutProductEntity", b =>
                {
                    b.Navigation("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
